### ISSUE TITLE
PermissionError: DMMClient: require admin permission

### ISSUE THREAD

**Issue by ddaodan** [Akegarasu/ok-derby#11]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "auto_derby\okderby.py", line 60, in start
  File "auto_derby\clients\dmm.py", line 52, in setup
PermissionError: DMMClient: require admin permission

以管理员身份运行dmm也会这样提示

**Comment by Akegarasu** [comment]
需要的是用管理员运行本程序，而不是dmm
